/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardComercialRouteImport } from './routes/_authenticated/dashboard-comercial'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedVendedoresRouteImport } from './routes/_authenticated/vendedores'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos.index'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated/orcamentos.$id'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos.index'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos.$id'
import { Route as AuthenticatedPreVendasIndexRouteImport } from './routes/_authenticated/pre-vendas.index'
import { Route as AuthenticatedPreVendasIdRouteImport } from './routes/_authenticated/pre-vendas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardComercialRoute =
  AuthenticatedDashboardComercialRouteImport.update({
    id: '/dashboard-comercial',
    path: '/dashboard-comercial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedoresRoute = AuthenticatedVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosIdRoute =
  AuthenticatedOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreVendasIndexRoute =
  AuthenticatedPreVendasIndexRouteImport.update({
    id: '/pre-vendas/',
    path: '/pre-vendas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreVendasIdRoute =
  AuthenticatedPreVendasIdRouteImport.update({
    id: '/pre-vendas/$id',
    path: '/pre-vendas/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard-comercial': typeof AuthenticatedDashboardComercialRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pre-vendas/$id': typeof AuthenticatedPreVendasIdRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/pre-vendas/': typeof AuthenticatedPreVendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard-comercial': typeof AuthenticatedDashboardComercialRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/pre-vendas/$id': typeof AuthenticatedPreVendasIdRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
  '/pre-vendas': typeof AuthenticatedPreVendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard-comercial': typeof AuthenticatedDashboardComercialRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vendedores': typeof AuthenticatedVendedoresRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/pre-vendas/$id': typeof AuthenticatedPreVendasIdRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
  '/_authenticated/pre-vendas/': typeof AuthenticatedPreVendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/dashboard-comercial'
    | '/estoque'
    | '/financeiro'
    | '/importacoes'
    | '/painel'
    | '/pendencias'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/vendedores'
    | '/orcamentos/$id'
    | '/pedidos/$id'
    | '/pre-vendas/$id'
    | '/orcamentos/'
    | '/pedidos/'
    | '/pre-vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/dashboard-comercial'
    | '/estoque'
    | '/financeiro'
    | '/importacoes'
    | '/painel'
    | '/pendencias'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/vendedores'
    | '/orcamentos/$id'
    | '/pedidos/$id'
    | '/pre-vendas/$id'
    | '/orcamentos'
    | '/pedidos'
    | '/pre-vendas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard-comercial'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/importacoes'
    | '/_authenticated/painel'
    | '/_authenticated/pendencias'
    | '/_authenticated/producao'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/vendedores'
    | '/_authenticated/orcamentos/$id'
    | '/_authenticated/pedidos/$id'
    | '/_authenticated/pre-vendas/$id'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/pedidos/'
    | '/_authenticated/pre-vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-comercial': {
      id: '/_authenticated/dashboard-comercial'
      path: '/dashboard-comercial'
      fullPath: '/dashboard-comercial'
      preLoaderRoute: typeof AuthenticatedDashboardComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedores': {
      id: '/_authenticated/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AuthenticatedVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/$id': {
      id: '/_authenticated/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pre-vendas/': {
      id: '/_authenticated/pre-vendas/'
      path: '/pre-vendas'
      fullPath: '/pre-vendas/'
      preLoaderRoute: typeof AuthenticatedPreVendasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pre-vendas/$id': {
      id: '/_authenticated/pre-vendas/$id'
      path: '/pre-vendas/$id'
      fullPath: '/pre-vendas/$id'
      preLoaderRoute: typeof AuthenticatedPreVendasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardComercialRoute: typeof AuthenticatedDashboardComercialRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVendedoresRoute: typeof AuthenticatedVendedoresRoute
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedPreVendasIdRoute: typeof AuthenticatedPreVendasIdRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
  AuthenticatedPreVendasIndexRoute: typeof AuthenticatedPreVendasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardComercialRoute: AuthenticatedDashboardComercialRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVendedoresRoute: AuthenticatedVendedoresRoute,
  AuthenticatedOrcamentosIdRoute: AuthenticatedOrcamentosIdRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedPreVendasIdRoute: AuthenticatedPreVendasIdRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
  AuthenticatedPreVendasIndexRoute: AuthenticatedPreVendasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
